CREATE TABLE IF NOT EXISTS `#__faqbookpro_voting` (
 `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `faq_id` int(11) unsigned NOT NULL,
 `user_id` int(10) unsigned DEFAULT NULL,
 `user_ip` varchar(25) DEFAULT NULL,
 `vote_up` smallint(5) unsigned NOT NULL DEFAULT '0',
 `vote_down` smallint(5) unsigned NOT NULL DEFAULT '0',
 `reason` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '1: Incorrect info, 2: Do not like, 3: Confusing, 4: Not an answer, 5: Too much, 6: Other',
 `published` tinyint(1) NOT NULL DEFAULT '0',
 `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `creation_date` datetime NOT NULL,
 `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
 `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__faqbookpro_content` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `asset_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the #__assets table.',
 `title` varchar(255) NOT NULL DEFAULT '',
 `alias` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
 `introtext` mediumtext NOT NULL,
 `fulltext` mediumtext NOT NULL,
 `state` tinyint(3) NOT NULL DEFAULT '0',
 `answered` tinyint(3) NOT NULL DEFAULT '0',
 `catid` int(10) unsigned NOT NULL DEFAULT '0',
 `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `created_by` int(10) unsigned NOT NULL DEFAULT '0',
 `created_by_alias` varchar(255) NOT NULL DEFAULT '',
 `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `modified_by` int(10) unsigned NOT NULL DEFAULT '0',
 `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
 `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `images` text NOT NULL,
 `urls` text NOT NULL,
 `attribs` varchar(5120) NOT NULL,
 `version` int(10) unsigned NOT NULL DEFAULT '1',
 `ordering` int(11) NOT NULL DEFAULT '0',
 `metakey` text NOT NULL,
 `metadesc` text NOT NULL,
 `access` int(10) unsigned NOT NULL DEFAULT '0',
 `hits` int(10) unsigned NOT NULL DEFAULT '0',
 `metadata` text NOT NULL,
 `featured` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Set if article is featured.',
 `language` char(7) NOT NULL COMMENT 'The language code for the article.',
 `xreference` varchar(50) NOT NULL COMMENT 'A reference to enable linkages to external data sets.',
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
